
import streamlit as st

def run_page():
    st.title("Idiosyncratic Readiness ($V^R$) Component")
    st.header("Conceptual Definition")
    st.markdown("Idiosyncratic Readiness ($V^R$) measures an individual's specific preparation to succeed in AI-enabled careers. Unlike systematic opportunity, these factors can be directly improved through deliberate learning and skill development.")
    st.markdown(r"The final Idiosyncratic Readiness score ($V^R(t)$) aggregates AI-Fluency, Domain-Expertise, and Adaptive-Capacity. This score quantifies an individual's personal preparation to succeed in AI-enabled careers, factors that can be directly improved through deliberate learning and skill development. It is a weighted sum:$$V^R(t) = w_{\text{VR1}} \cdot AI\text{-}Fluency_i(t) + w_{\text{VR2}} \cdot Domain\text{-}Expertise_i(t) + w_{\text{VR3}} \cdot Adaptive\text{-}Capacity_i(t)$$")
    st.markdown(r"The weights ($w_{\text{VR1}} = 0.45$, $w_{\text{VR2}} = 0.35$, $w_{\text{VR3}} = 0.20$) reflect the assessment that AI-Fluency is the most critical factor, followed by Domain-Expertise, with Adaptive-Capacity playing a supporting role (weights are from `PARAMS`). The final $V^R$ score is normalized to $[0, 100]$.")
    st.markdown("This completes the calculation of the individual-specific readiness component. The $V^R$ score provides a holistic view of an individual's intrinsic capabilities and potential for growth in AI-driven roles, serving as a critical counterpart to the market-driven $H^R$.")

    st.subheader("AI-Fluency Factor")
    st.markdown("The AI-Fluency factor is a key sub-component, representing the ability to effectively use, understand, and collaborate with AI systems. It is calculated as a weighted sum of four sub-components:")
    st.markdown(r"$$AI\text{-}Fluency_i = \sum_{k=1}^4 \theta_k \cdot S_{i,k}$$")
    st.markdown(r"The sub-components ($S_{i,k}$) and their weights ($\theta_k$ from `PARAMS`) are:")
    st.markdown("**1. Technical AI Skills** ($S_{i,1}$, $\theta_1 = 0.30$): Based on Prompting, Tools, Understanding, and Data Literacy scores.")
    st.markdown(r"$$S_{i,1} = \frac{1}{4} (\text{Prompting}_i + \text{Tools}_i + \text{Understanding}_i + \text{DataLit}_i)$$")
    st.markdown("**2. AI-Augmented Productivity** ($S_{i,2}$, $\theta_2 = 0.35$): Measures productivity gains with AI assistance.")
    st.markdown(r"$$S_{i,2} = \frac{\text{Output Quality}_{i,\text{with AI}}}{\text{Output Quality}_{i,\text{without AI}}} \cdot \frac{\text{Time}_{i,\text{without AI}}}{\text{Time}_{i,\text{with AI}}}$$")
    st.markdown("For simplicity, our synthetic data has `ai_augmented_productivity_norm` pre-calculated based on this concept.")
    st.markdown("**3. Critical AI Judgment** ($S_{i,3}$, $\theta_3 = 0.20$): Assesses error detection and appropriate trust decisions with AI outputs.")
    st.markdown(r"$$S_{i,3} = \frac{\text{Errors Caught}_i}{\text{Total AI Errors}} + \frac{\text{Appropriate Trust Decisions}_i}{\text{Total Decisions}}$$")
    st.markdown("For simplicity, our synthetic data provides `errors_caught_norm` and `trust_decisions_norm` which we'll combine and re-normalize.")
    st.markdown("**4. AI Learning Velocity** ($S_{i,4}$, $\theta_4 = 0.15$): Measures improvement rate per unit time investment.")
    st.markdown(r"$$S_{i,4} = \frac{\Delta Proficiency_i}{\Delta t} \cdot \frac{1}{\text{Hours Invested}}$$")
    st.markdown("For simplicity in this notebook, $\Delta Proficiency_i / \Delta t$ can be approximated as a 'learning_rate' for simulation purposes and then scaled with `hours_invested`.")
    st.markdown("The AI-Fluency score provides a detailed individual assessment of an employee's ability to interact with and leverage AI technologies. This multi-faceted measure highlights specific areas where an individual might excel or need further development in their AI-related capabilities.")

    st.subheader("Domain-Expertise Factor")
    st.markdown("Domain-Expertise captures an individual's depth of knowledge in specific application areas, complementing their AI-Fluency. It is a multiplicative combination of Educational Foundation, Practical Experience, and Specialization Depth:")
    st.markdown(r"$$Domain\text{-}Expertise_i = E_{\text{education}} \cdot E_{\text{experience}} \cdot E_{\text{specialization}}$$")
    st.markdown("**1. Educational Foundation ($E_{\text{education}}$):** Discrete values based on education level (e.g., PhD=1.0, Master's=0.85, Bachelor's=0.70, Associate's/Certificate=0.60, HS+Coursework=0.50).")
    st.markdown(r"**2. Practical Experience ($E_{\text{experience}}$):** Measured by years of experience with diminishing returns:$$E_{\text{experience}} = 1 - e^{-\gamma_{\text{exp}} \cdot Years}$$")
    st.markdown(r"where $\gamma_{\text{exp}} = 0.15$.")
    st.markdown("**3. Specialization Depth ($E_{\text{specialization}}$):** Reflects specific achievements and recognition in their field:")
    st.markdown(r"$$E_{\text{specialization}} = w_{\text{port}} \cdot \text{Portfolio}_i + w_{\text{recog}} \cdot \text{Recognition}_i + w_{\text{cred}} \cdot \text{Credentials}_i$$")
    st.markdown(r"where $w_{\text{port}} = 0.4$, $w_{\text{recog}} = 0.3$, $w_{\text{cred}} = 0.3$.")
    st.markdown("Domain-Expertise underscores the importance of deep, specialized knowledge in specific fields, which AI tools are designed to augment. This score provides a quantitative measure of an individual's subject matter mastery, a crucial complement to their AI-Fluency.")

    st.subheader("Adaptive-Capacity Factor")
    st.markdown("Adaptive-Capacity measures the meta-skills that enable successful navigation of AI-driven transitions, focusing on an individual's ability to learn, adapt, and interact effectively in new environments. It is an equally weighted sum of three meta-skills:")
    st.markdown(r"$$Adaptive\text{-}Capacity_i = \frac{1}{3} (C_{\text{cognitive}} + C_{\text{social}} + C_{\text{strategic}})$$")
    st.markdown(r"where each $C$ component is scored on a scale of $[0, 100]$:")
    st.markdown("*   **Cognitive Flexibility ($C_{\text{cognitive}}$):** Problem-solving in novel contexts, transfer learning, creative application of AI tools.")
    st.markdown("*   **Social-Emotional Intelligence ($C_{\text{social}}$):** Empathy, negotiation, leadership, human-AI collaboration.")
    st.markdown("*   **Strategic Career Management ($C_{\text{strategic}}$):** Awareness of AI trends, proactive skill development, network building.")
    st.markdown("Adaptive-Capacity highlights an individual's inherent ability to thrive in a rapidly changing AI landscape. These meta-skills are increasingly vital for sustained career success, as they enable individuals to continuously learn, adapt, and collaborate effectively with both humans and AI.")
